import "@/styles/globals.css";

import { StackProvider, StackTheme } from "@stackframe/stack";
import { GeistSans as FontSans } from "geist/font/sans";
import { type Metadata } from "next";
import { stackServerApp } from "../stack";

import { cn } from "@/lib/utils";
import { TRPCReactProvider } from "@/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={cn(
        "min-h-screen bg-background antialiased",
        "font-sans font-normal leading-relaxed",
        FontSans.variable,
      )}
    >
      <body>
        <StackProvider app={stackServerApp}>
          <StackTheme>
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </StackTheme>
        </StackProvider>
      </body>
    </html>
  );
}
